services:
  service-main:
    build: .
    ports:
      - 3000:3000
    volumes:
      - "./flow-projects:/flowrs-build/flow-projects"
      - "./flow-projects:/flowrs-build/flow-packages"
    environment:
      - HOST_IP_1=0
      - HOST_IP_2=0
      - HOST_IP_3=0
      - HOST_IP_4=0
      - HOST_PORT=3000
