http://127.0.0.1:3000/projects/

###

POST http://127.0.0.1:3000/compile_jobs/ HTTP/1.1
content-type: application/json
{
    "project-name": "flow_project_1"
}

Response: {"job-id": "1234"}

http://127.0.0.1:3000/compile_jobs/1234/state

Response: 

###


POST http://127.0.0.1:3000/projects/ HTTP/1.1
content-type: application/json

{
  "name": "flow_project_17",
  "version": "1.0.0",
  "packages": [
    {"name": "flowrs", "version": "1.0.0", "path": "../../../flowrs"}, 
    {"name": "flowrs-std", "version": "1.0.0", "path": "../../../flowrs-std"}
    ],
  "flow":{        
        "nodes": {
            "node1": {
                "node_type": "flowrs_std::nodes::debug::DebugNode",
                "type_parameters": {"I": "i32"},
                "constructor": "New"

            },
            "node2": {
                "node_type": "flowrs_std::nodes::value::ValueNode",
                "type_parameters": {"I": "i32"},
                "constructor": "New"

            }
        },
        "connections": [
            {
                "input_node": "node2",
                "output_node": "node1",
                "input": "input",
                "output": "output"
            }
        ], 
        "data" : {
            "node2": {
                "value": 23
            }
        }
    }
}