http://127.0.0.1:3000/api/projects/

###

http://127.0.0.1:3000/api/packages/

####

POST http://127.0.0.1:3000/api/projects/flow_project_201/compile?build_type=cargo

####

POST http://127.0.0.1:3000/api/projects/flow_project_79/compile?build_type=wasm

###

POST http://127.0.0.1:3000/api/projects/flow_project_79/run?build_type=cargo

Response: {"process_id":18940}

###

POST http://127.0.0.1:3000/api/projects/flow_project_79/run?build_type=wasm

Response: {"process_id":18940}

###

POST http://127.0.0.1:3000/api/processes/18940/stop

###

GET http://127.0.0.1:3000/api/processes/18940/logs

###

POST http://127.0.0.1:3000/api/projects/ HTTP/1.1
content-type: application/json

{
  "name": "flow_project_201",
  "version": "1.0.0",
  "packages": [
    {"name": "flowrs", "version": "1.0.0", "path": "../../../flowrs"}, 
    {"name": "flowrs-std", "version": "1.0.0", "path": "../../../flowrs-std"}
    ],
  "flow":{        
        "nodes": {
            "debug_node": {
                "node_type": "flowrs_std::nodes::debug::DebugNode",
                "type_parameters": {"I": "i32"},
                "constructor": "New"

            },
            "timer_config_node": {
                "node_type": "flowrs_std::nodes::value::ValueNode",
                "type_parameters": {"I": "flowrs_std::nodes::timer::TimerNodeConfig"},
                "constructor": "New"

            },
            "timer_token_node": {
                "node_type": "flowrs_std::nodes::value::ValueNode",
                "type_parameters": {"I": "i32"},
                "constructor": "New"

            },
             "timer_node": {
                "node_type": "flowrs_std::nodes::timer::TimerNode",
                "type_parameters": {"T": "flowrs_std::nodes::timer::SelectedTimer", "U": "i32"},
                "constructor": "New"
            }
        },
        "connections": [
            {
                "from_node": "timer_config_node",
                "from_output": "output",
                "to_node": "timer_node",
                "to_input": "config_input"
            },
            {
                "from_node": "timer_token_node",
                "from_output": "output",
                "to_node": "timer_node",
                "to_input": "token_input"
            },
            {
                "from_node": "timer_node",
                "from_output": "token_output",
                "to_node": "debug_node",
                "to_input": "input"
            }
        ], 
        "data" : {
            "timer_config_node": {
                "value": {"duration": {"secs": 1, "nanos": 0}}
            },
             "timer_token_node": {
                "value": 42
            }
        }
    }
}