{
 "title": "Flowrs Live Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Node updates per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flowrs_node_update_time_count{job=~\"$job\"}[$__rate_interval]) ",
     "legendFormat": "{{node_name}} (id={{node_id}}, job={{job}})"
    }
   ]
  },
  {
   "title": "Average node update duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "rate(flowrs_node_update_time_sum{job=~\"$job\"}[$__rate_interval]) / rate(flowrs_node_update_time_count{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{node_name}} (id={{node_id}}, job={{job}})"
    }
   ]
  },
  {
   "title": "Node Connection Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(flowrs_node_edge_send_bytes{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Total Send (job={{job}})"
    },
    {
     "expr": "rate(flowrs_node_edge_receive_bytes{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Total Receive (job={{job}})"
    }
   ]
  },
  {
   "title": "Node Connection Message Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(flowrs_node_edge_send_count{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Total Send (job={{job}})"
    },
    {
     "expr": "rate(flowrs_node_edge_receive_count{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Total Receive (job={{job}})"
    }
   ]
  }
 ]
}