import { ChatOpenAI } from "@langchain/openai";
import { JsonOutputParser } from "@langchain/core/output_parsers";
//import { chatprompttemplate } from "@langchain/core/prompts";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";


export async function useOpenAI(prompt: string) {

    /*
    * Opening an Instance of ChatGPT using the Users API key.
    */
    const model = new ChatOpenAI({
        model: "gpt-4o-mini", openAIApiKey: ""
    });

    
    // Due to OpenAi answering with alot of Data a JSON Parser is used to extract the J
    const parser = new JsonOutputParser();

    
    // This prompt is used to ensure correct results.
    const messages = [
        new SystemMessage("We have a flow based programming lanugage. It's has three types of nodes.  Timer Nodes which specify intervalls of triggering an event.  A Json schema for an value would look like this: \"timer_node: {"
            + "node_type: \"flowrs_std::nodes::timer::TimerNode\""
            + "type_paramters: {"
            + "T: \"flowrs_std::nodes::timer::SelectedTimer\""
            + "U: \"i32\","
            + "},"
            + "constructor: \"New\""
            + "}\" \"timer_node\"represents the name of the node, can be changed, must be unique and is used as the identifier of the node in connections and data."
            + "Value Nodes which either specify a 32 bit signed integer.A Json schema for an value node would look like this:"
            + "\"value_node: {"
            + "node_type: \"flowrs_std::nodes::value::ValueNode\""
            + "type_paramters: {"
            + "I: \"i32\""
            + " },"
            + "constructor: \"New\""
            + "} "
            + "\"value_node\"represents the name of the node, can be changed, must be unique and is used as the identifier of the node in connections and data."
            + "Value Nodes can also specify the interval in which Timer Nodes repeat signals. The Json Schema for such a Value Node would look like this: \"timer_config_node\": {"
            + "\"node_type\": \"flowrs_std::nodes::value::ValueNode\","
            + "\"type_parameters\": {"
            + "\"I\": \"flowrs_std::nodes::timer::TimerNodeConfig\""
            + "},"
            + "\"constructor\": \"New\""
            + "} \" \"timer_config_node\"represents the name of the node, can be changed, must be unique and is used as the identifier of the node in connections and data."
            + "Debug Nodes which are used to print out to the console. A Json schema for a value would look like this:"
            + "debug_node?: {\""
            + "node_type: \"flowrs_std::nodes::debug::DebugNode\""
            + "type_paramters: {"
            + "I: \"i32\""
            + "},"
            + "constructor: \"New\""
            + "} "
            + "\"debug_node\"represents the name of the node, must be unique and is used as the identifier of the node in connections and data."
            + "Nodes are connected by connections.Value Nodes have an Output called \"Output\".Timer Nodes have two inputs.One for a value node with an integer called \"token_input\" and one for value node with the Timer that gives the interval in which the Timer Node triggers called \"config_input\".Timer Nodes have an Output which sends a signal to debug nodes called \"token_output\".The debug Node has an input called \"Input\".The Json Schema for a connection looks like this:"
            + "\"{"
            + "from_node: String,"
            + "to_node: String,"
            + "to_input: String,"
            + "from_output: String"
            + "}\""
            + "Values for Value Nodes are written in Data.The Json Schema for integers is:"
            + "\"timer_token_node\": {"
            + "\"value\": i32"
            + "}"
            + "The Json Schema for value nodes with timers is:"
            + "\"timer_config_node\": {"
            + "\"value\": {"
            + "\"duration\": {"
            + "\"nanos\": 0,"
            + "\"secs\": 1"
            + "}"
            + "}"
            + "}"
            + "The value for nanos cant exceed"
            + "A example for a full Json would be:"
            + "\"nodes\": {"
            + "\"timer_node\": {"
            + "\"node_type\": \"flowrs_std::nodes::timer::TimerNode\","
            + "\"type_parameters\": {"
            + "\"T\": \"flowrs_std::nodes::timer::SelectedTimer\""
            + "\"U\": \"i32\","
            + "},"
            + "\"constructor\": \"New\""
            + "},"
            + "\"timer_config_node\": {"
            + "\"node_type\": \"flowrs_std::nodes::value::ValueNode\","
            + "\"type_parameters\": {"
            + "\"I\": \"flowrs_std::nodes::timer::TimerNodeConfig\""
            + "},"
            + "\"constructor\": \"New\""
            + "},"
            + "\"debug_node\": {"
            + "\"node_type\": \"flowrs_std::nodes::debug::DebugNode\","
            + "\"type_parameters\": {"
            + "\"I\": \"i32\""
            + "},"
            + "\"constructor\": \"New\""
            + "},"
            + "\"timer_token_node\": {"
            + "\"node_type\": \"flowrs_std::nodes::value::ValueNode\","
            + "\"type_parameters\": {"
            + "\"I\": \"i32\""
            + "},"
            + "\"constructor\": \"New\""
            + "}"
            + "},"
            + "\"connections\": ["
            + "{"
            + "\"from_node\": \"timer_config_node\","
            + "\"to_node\": \"timer_node\","
            + "\"to_input\": \"config_input\","
            + "\"from_output\": \"output\""
            + "},"
            + "{"
            + "\"from_node\": \"timer_token_node\","
            + "\"to_node\": \"timer_node\","
            + "\"to_input\": \"token_input\","
            + "\"from_output\": \"output\""
            + "},"
            + "{"
            + "\"from_node\": \"timer_node\","
            + "\"to_node\": \"debug_node\","
            + "\"to_input\": \"input\","
            + "\"from_output\": \"token_output\""
            + "}"
            + "],"
            + "\"data\": {"
            + "\"timer_config_node\": {"
            + "\"value\": {"
            + "\"duration\": {"
            + "\"nanos\": 0,"
            + "\"secs\": 1"
            + "}"
            + "}"
            + "},"
            + "\"timer_token_node\": {"
            + "\"value\": 42"
            + "}"
            + "}"
            + "Respond with a valid JSON object, containing three fields: 'nodes', 'connections' and 'data'."),
        new HumanMessage(prompt),
    ];

    const result = await model.invoke(messages);
    const finishedJson = await parser.invoke(result);
    return finishedJson;
}
    // A query and format instructions used to prompt a language model.
//    const flowQuery = prompt;
//    const formatInstructions =
//        "We have a flow based programming lanugage. It's has three types of nodes.  Timer Nodes which specify intervalls of triggering an event.  A Json schema for an value would look like this: \"timer_node: {"
//           + "node_type: \"flowrs_std::nodes::timer::TimerNode\""
//            + "type_paramters: {"
//                + "I: \"i32\","
//                + "T: \"flowrs_std::nodes::timer::SelectedTimer\""
//            + "},"
//            + "constructor: \"New\""
//        + "}\" \"timer_node\"represents the name of the node, can be changed, must be unique and is used as the identifier of the node in connections and data."
//        + "Value Nodes which either specify a 32 bit signed integer.A Json schema for an value node would look like this:"
//        + "debug_node?: {\""
//    + "node_type: \"flowrs_std::nodes::debug::DebugNode\""
//    + "type_paramters: {"
//        + "I: \"i32\""
//    + "},"
//    + "constructor: \"New\""
//+ "} \""
//    + "\"debug_node\"represents the name of the node, can be changed, must be unique and is used as the identifier of the node in connections and data."
//+ "Value Nodes can also specify the interval in which Timer Nodes repeat signals.The Json Schema for such a Value Node would look like this: \"timer_config_node\": {"
//        + "\"node_type\": \"flowrs_std::nodes::value::ValueNode\","
//            + "\"type_parameters\": {"
//            + "\"I\": \"flowrs_std::nodes::timer::TimerNodeConfig\""
//        + "},"
//        + "\"constructor\": \"New\""
//    + "} \" \"timer_config_node\"represents the name of the node, can be changed, must be unique and is used as the identifier of the node in connections and data."
//+ "Debug Nodes which are used to print out to the console.A Json schema for an value would look like this:"
//    + "\"value_node: {"
//    + "node_type: \"flowrs_std::nodes::value::ValueNode\""
//    + "type_paramters: {"
//        + "I: \"i32\""
//   + " },"
//    + "constructor: \"New\""
//+ "} \" \"value_node\"represents the name of the node, must be unique and is used as the identifier of the node in connections and data."
//+ "Nodes are connected by connections.Value Nodes have an Output called \"Output\".Timer Nodes have two inputs.One for a value node with an integer called \"token_input\" and one for value node with the Timer that gives the interval in which the Timer Node triggers called \"config_input\".Timer Nodes have an Output which sends a signal to debug nodes called \"token_output\".The debug Node has an input called \"Input\".The Json Schema for a connection looks like this:"
//+ "\"{"
//+ "from_node: String,"
//    + "to_node: String,"
//       + "to_input: String,"
//           + "from_output: String"
//      + "}\""
//+ "Values for Value Nodes are written in Data.The Json Schema for integers is:"
//    + "\"timer_token_node\": {"
//    + "\"value\": i32"
//+ "}" 
//+ "The Json Schema for value nodes with timers is:"
//    + "\"timer_config_node\": {"
//    + "\"value\": {"
//        + "\"duration\": {"
//            + "\"nanos\": 0,"
//                + "\"secs\": 1"
//        + "}"
//    + "}"
//+ "}"
//+ "A example for a full Json would be:"
//+ "\"nodes\": {"
//    + "\"timer_node\": {"
//        + "\"node_type\": \"flowrs_std::nodes::timer::TimerNode\","
//            + "\"type_parameters\": {"
//            + "\"U\": \"i32\","
//                + "\"T\": \"flowrs_std::nodes::timer::SelectedTimer\""
//        + "},"
//        + "\"constructor\": \"New\""
//    + "},"
//    + "\"timer_config_node\": {"
//        + "\"node_type\": \"flowrs_std::nodes::value::ValueNode\","
//            + "\"type_parameters\": {"
//            + "\"I\": \"flowrs_std::nodes::timer::TimerNodeConfig\""
//        + "},"
//        + "\"constructor\": \"New\""
//    + "},"
//    + "\"debug_node\": {"
//        + "\"node_type\": \"flowrs_std::nodes::debug::DebugNode\","
//            + "\"type_parameters\": {"
//            + "\"I\": \"i32\""
//        + "},"
//        + "\"constructor\": \"New\""
//    + "},"
//    + "\"timer_token_node\": {"
//        + "\"node_type\": \"flowrs_std::nodes::value::ValueNode\","
//            + "\"type_parameters\": {"
//            + "\"I\": \"i32\""
//        + "},"
//        + "\"constructor\": \"New\""
//    + "}"
//+ "},"
//+ "\"connections\": ["
//    + "{"
//        + "\"from_node\": \"timer_config_node\","
//        + "\"to_node\": \"timer_node\","
//        + "\"to_input\": \"config_input\","
//        + "\"from_output\": \"output\""
//    + "},"
//    + "{"
//        + "\"from_node\": \"timer_token_node\","
//        + "\"to_node\": \"timer_node\","
//        + "\"to_input\": \"token_input\","
//        + "\"from_output\": \"output\""
//    + "},"
//    + "{"
//        + "\"from_node\": \"timer_node\","
//        + "\"to_node\": \"debug_node\","
//        + "\"to_input\": \"input\","
//        + "\"from_output\": \"token_output\""
//    + "}"
//+ "],"
//    + "\"data\": {"
//    + "\"timer_config_node\": {"
//        + "\"value\": {"
//            + "\"duration\": {"
//                + "\"nanos\": 0,"
//                    + "\"secs\": 1"
//            + "}"
//        + "}"
//    + "},"
//    + "\"timer_token_node\": {"
//        + "\"value\": 42"
//    + "}"
//+ "}"
//+ "Respond with a valid JSON object, containing three fields: 'nodes', 'connections' and 'data'."
    

//    const finishedPrompt = ChatPromptTemplate.fromTemplate(
//        "Answer the user query.\n{format_instructions}\n{query}\n"
//    );

//    const partialedPrompt = await finishedPrompt.partial({
//        format_instructions: formatInstructions,
//    });

//    const chain = partialedPrompt.pipe(model).pipe(parser);


//    await chain.invoke({ query: flowQuery });
// }